/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var hedgehog_protocol_proto_ack_pb = require('./ack_pb.js');
var hedgehog_protocol_proto_io_pb = require('./io_pb.js');
var hedgehog_protocol_proto_motor_pb = require('./motor_pb.js');
var hedgehog_protocol_proto_servo_pb = require('./servo_pb.js');
var hedgehog_protocol_proto_process_pb = require('./process_pb.js');
goog.exportSymbol('proto.hedgehog.protocol.proto.HedgehogMessage', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hedgehog.protocol.proto.HedgehogMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_);
};
goog.inherits(proto.hedgehog.protocol.proto.HedgehogMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hedgehog.protocol.proto.HedgehogMessage.displayName = 'proto.hedgehog.protocol.proto.HedgehogMessage';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_ = [[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]];

/**
 * @enum {number}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  ACKNOWLEDGEMENT: 1,
  IO_STATE_ACTION: 2,
  ANALOG_REQUEST: 3,
  ANALOG_UPDATE: 4,
  DIGITAL_REQUEST: 5,
  DIGITAL_UPDATE: 6,
  MOTOR_ACTION: 7,
  MOTOR_REQUEST: 8,
  MOTOR_UPDATE: 9,
  MOTOR_STATE_UPDATE: 10,
  MOTOR_SET_POSITION_ACTION: 11,
  SERVO_ACTION: 12,
  PROCESS_EXECUTE_REQUEST: 13,
  PROCESS_EXECUTE_REPLY: 14,
  PROCESS_STREAM_ACTION: 15,
  PROCESS_STREAM_UPDATE: 16,
  PROCESS_EXIT_UPDATE: 17
};

/**
 * @return {proto.hedgehog.protocol.proto.HedgehogMessage.PayloadCase}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getPayloadCase = function() {
  return /** @type {proto.hedgehog.protocol.proto.HedgehogMessage.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.hedgehog.protocol.proto.HedgehogMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hedgehog.protocol.proto.HedgehogMessage} msg The msg instance to transform.
 * @return {!Object}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    acknowledgement: (f = msg.getAcknowledgement()) && hedgehog_protocol_proto_ack_pb.Acknowledgement.toObject(includeInstance, f),
    ioStateAction: (f = msg.getIoStateAction()) && hedgehog_protocol_proto_io_pb.IOStateAction.toObject(includeInstance, f),
    analogRequest: (f = msg.getAnalogRequest()) && hedgehog_protocol_proto_io_pb.AnalogRequest.toObject(includeInstance, f),
    analogUpdate: (f = msg.getAnalogUpdate()) && hedgehog_protocol_proto_io_pb.AnalogUpdate.toObject(includeInstance, f),
    digitalRequest: (f = msg.getDigitalRequest()) && hedgehog_protocol_proto_io_pb.DigitalRequest.toObject(includeInstance, f),
    digitalUpdate: (f = msg.getDigitalUpdate()) && hedgehog_protocol_proto_io_pb.DigitalUpdate.toObject(includeInstance, f),
    motorAction: (f = msg.getMotorAction()) && hedgehog_protocol_proto_motor_pb.MotorAction.toObject(includeInstance, f),
    motorRequest: (f = msg.getMotorRequest()) && hedgehog_protocol_proto_motor_pb.MotorRequest.toObject(includeInstance, f),
    motorUpdate: (f = msg.getMotorUpdate()) && hedgehog_protocol_proto_motor_pb.MotorUpdate.toObject(includeInstance, f),
    motorStateUpdate: (f = msg.getMotorStateUpdate()) && hedgehog_protocol_proto_motor_pb.MotorStateUpdate.toObject(includeInstance, f),
    motorSetPositionAction: (f = msg.getMotorSetPositionAction()) && hedgehog_protocol_proto_motor_pb.MotorSetPositionAction.toObject(includeInstance, f),
    servoAction: (f = msg.getServoAction()) && hedgehog_protocol_proto_servo_pb.ServoAction.toObject(includeInstance, f),
    processExecuteRequest: (f = msg.getProcessExecuteRequest()) && hedgehog_protocol_proto_process_pb.ProcessExecuteRequest.toObject(includeInstance, f),
    processExecuteReply: (f = msg.getProcessExecuteReply()) && hedgehog_protocol_proto_process_pb.ProcessExecuteReply.toObject(includeInstance, f),
    processStreamAction: (f = msg.getProcessStreamAction()) && hedgehog_protocol_proto_process_pb.ProcessStreamAction.toObject(includeInstance, f),
    processStreamUpdate: (f = msg.getProcessStreamUpdate()) && hedgehog_protocol_proto_process_pb.ProcessStreamUpdate.toObject(includeInstance, f),
    processExitUpdate: (f = msg.getProcessExitUpdate()) && hedgehog_protocol_proto_process_pb.ProcessExitUpdate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hedgehog.protocol.proto.HedgehogMessage}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hedgehog.protocol.proto.HedgehogMessage;
  return proto.hedgehog.protocol.proto.HedgehogMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hedgehog.protocol.proto.HedgehogMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hedgehog.protocol.proto.HedgehogMessage}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new hedgehog_protocol_proto_ack_pb.Acknowledgement;
      reader.readMessage(value,hedgehog_protocol_proto_ack_pb.Acknowledgement.deserializeBinaryFromReader);
      msg.setAcknowledgement(value);
      break;
    case 2:
      var value = new hedgehog_protocol_proto_io_pb.IOStateAction;
      reader.readMessage(value,hedgehog_protocol_proto_io_pb.IOStateAction.deserializeBinaryFromReader);
      msg.setIoStateAction(value);
      break;
    case 3:
      var value = new hedgehog_protocol_proto_io_pb.AnalogRequest;
      reader.readMessage(value,hedgehog_protocol_proto_io_pb.AnalogRequest.deserializeBinaryFromReader);
      msg.setAnalogRequest(value);
      break;
    case 4:
      var value = new hedgehog_protocol_proto_io_pb.AnalogUpdate;
      reader.readMessage(value,hedgehog_protocol_proto_io_pb.AnalogUpdate.deserializeBinaryFromReader);
      msg.setAnalogUpdate(value);
      break;
    case 5:
      var value = new hedgehog_protocol_proto_io_pb.DigitalRequest;
      reader.readMessage(value,hedgehog_protocol_proto_io_pb.DigitalRequest.deserializeBinaryFromReader);
      msg.setDigitalRequest(value);
      break;
    case 6:
      var value = new hedgehog_protocol_proto_io_pb.DigitalUpdate;
      reader.readMessage(value,hedgehog_protocol_proto_io_pb.DigitalUpdate.deserializeBinaryFromReader);
      msg.setDigitalUpdate(value);
      break;
    case 7:
      var value = new hedgehog_protocol_proto_motor_pb.MotorAction;
      reader.readMessage(value,hedgehog_protocol_proto_motor_pb.MotorAction.deserializeBinaryFromReader);
      msg.setMotorAction(value);
      break;
    case 8:
      var value = new hedgehog_protocol_proto_motor_pb.MotorRequest;
      reader.readMessage(value,hedgehog_protocol_proto_motor_pb.MotorRequest.deserializeBinaryFromReader);
      msg.setMotorRequest(value);
      break;
    case 9:
      var value = new hedgehog_protocol_proto_motor_pb.MotorUpdate;
      reader.readMessage(value,hedgehog_protocol_proto_motor_pb.MotorUpdate.deserializeBinaryFromReader);
      msg.setMotorUpdate(value);
      break;
    case 10:
      var value = new hedgehog_protocol_proto_motor_pb.MotorStateUpdate;
      reader.readMessage(value,hedgehog_protocol_proto_motor_pb.MotorStateUpdate.deserializeBinaryFromReader);
      msg.setMotorStateUpdate(value);
      break;
    case 11:
      var value = new hedgehog_protocol_proto_motor_pb.MotorSetPositionAction;
      reader.readMessage(value,hedgehog_protocol_proto_motor_pb.MotorSetPositionAction.deserializeBinaryFromReader);
      msg.setMotorSetPositionAction(value);
      break;
    case 12:
      var value = new hedgehog_protocol_proto_servo_pb.ServoAction;
      reader.readMessage(value,hedgehog_protocol_proto_servo_pb.ServoAction.deserializeBinaryFromReader);
      msg.setServoAction(value);
      break;
    case 13:
      var value = new hedgehog_protocol_proto_process_pb.ProcessExecuteRequest;
      reader.readMessage(value,hedgehog_protocol_proto_process_pb.ProcessExecuteRequest.deserializeBinaryFromReader);
      msg.setProcessExecuteRequest(value);
      break;
    case 14:
      var value = new hedgehog_protocol_proto_process_pb.ProcessExecuteReply;
      reader.readMessage(value,hedgehog_protocol_proto_process_pb.ProcessExecuteReply.deserializeBinaryFromReader);
      msg.setProcessExecuteReply(value);
      break;
    case 15:
      var value = new hedgehog_protocol_proto_process_pb.ProcessStreamAction;
      reader.readMessage(value,hedgehog_protocol_proto_process_pb.ProcessStreamAction.deserializeBinaryFromReader);
      msg.setProcessStreamAction(value);
      break;
    case 16:
      var value = new hedgehog_protocol_proto_process_pb.ProcessStreamUpdate;
      reader.readMessage(value,hedgehog_protocol_proto_process_pb.ProcessStreamUpdate.deserializeBinaryFromReader);
      msg.setProcessStreamUpdate(value);
      break;
    case 17:
      var value = new hedgehog_protocol_proto_process_pb.ProcessExitUpdate;
      reader.readMessage(value,hedgehog_protocol_proto_process_pb.ProcessExitUpdate.deserializeBinaryFromReader);
      msg.setProcessExitUpdate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.hedgehog.protocol.proto.HedgehogMessage} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.hedgehog.protocol.proto.HedgehogMessage.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getAcknowledgement();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      hedgehog_protocol_proto_ack_pb.Acknowledgement.serializeBinaryToWriter
    );
  }
  f = this.getIoStateAction();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      hedgehog_protocol_proto_io_pb.IOStateAction.serializeBinaryToWriter
    );
  }
  f = this.getAnalogRequest();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      hedgehog_protocol_proto_io_pb.AnalogRequest.serializeBinaryToWriter
    );
  }
  f = this.getAnalogUpdate();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      hedgehog_protocol_proto_io_pb.AnalogUpdate.serializeBinaryToWriter
    );
  }
  f = this.getDigitalRequest();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      hedgehog_protocol_proto_io_pb.DigitalRequest.serializeBinaryToWriter
    );
  }
  f = this.getDigitalUpdate();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      hedgehog_protocol_proto_io_pb.DigitalUpdate.serializeBinaryToWriter
    );
  }
  f = this.getMotorAction();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      hedgehog_protocol_proto_motor_pb.MotorAction.serializeBinaryToWriter
    );
  }
  f = this.getMotorRequest();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      hedgehog_protocol_proto_motor_pb.MotorRequest.serializeBinaryToWriter
    );
  }
  f = this.getMotorUpdate();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      hedgehog_protocol_proto_motor_pb.MotorUpdate.serializeBinaryToWriter
    );
  }
  f = this.getMotorStateUpdate();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      hedgehog_protocol_proto_motor_pb.MotorStateUpdate.serializeBinaryToWriter
    );
  }
  f = this.getMotorSetPositionAction();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      hedgehog_protocol_proto_motor_pb.MotorSetPositionAction.serializeBinaryToWriter
    );
  }
  f = this.getServoAction();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      hedgehog_protocol_proto_servo_pb.ServoAction.serializeBinaryToWriter
    );
  }
  f = this.getProcessExecuteRequest();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      hedgehog_protocol_proto_process_pb.ProcessExecuteRequest.serializeBinaryToWriter
    );
  }
  f = this.getProcessExecuteReply();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      hedgehog_protocol_proto_process_pb.ProcessExecuteReply.serializeBinaryToWriter
    );
  }
  f = this.getProcessStreamAction();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      hedgehog_protocol_proto_process_pb.ProcessStreamAction.serializeBinaryToWriter
    );
  }
  f = this.getProcessStreamUpdate();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      hedgehog_protocol_proto_process_pb.ProcessStreamUpdate.serializeBinaryToWriter
    );
  }
  f = this.getProcessExitUpdate();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      hedgehog_protocol_proto_process_pb.ProcessExitUpdate.serializeBinaryToWriter
    );
  }
};


/**
 * optional Acknowledgement acknowledgement = 1;
 * @return {?proto.hedgehog.protocol.proto.Acknowledgement}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getAcknowledgement = function() {
  return /** @type{?proto.hedgehog.protocol.proto.Acknowledgement} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_ack_pb.Acknowledgement, 1));
};


/** @param {?proto.hedgehog.protocol.proto.Acknowledgement|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setAcknowledgement = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearAcknowledgement = function() {
  this.setAcknowledgement(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasAcknowledgement = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional IOStateAction io_state_action = 2;
 * @return {?proto.hedgehog.protocol.proto.IOStateAction}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getIoStateAction = function() {
  return /** @type{?proto.hedgehog.protocol.proto.IOStateAction} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_io_pb.IOStateAction, 2));
};


/** @param {?proto.hedgehog.protocol.proto.IOStateAction|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setIoStateAction = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearIoStateAction = function() {
  this.setIoStateAction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasIoStateAction = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional AnalogRequest analog_request = 3;
 * @return {?proto.hedgehog.protocol.proto.AnalogRequest}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getAnalogRequest = function() {
  return /** @type{?proto.hedgehog.protocol.proto.AnalogRequest} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_io_pb.AnalogRequest, 3));
};


/** @param {?proto.hedgehog.protocol.proto.AnalogRequest|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setAnalogRequest = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearAnalogRequest = function() {
  this.setAnalogRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasAnalogRequest = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional AnalogUpdate analog_update = 4;
 * @return {?proto.hedgehog.protocol.proto.AnalogUpdate}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getAnalogUpdate = function() {
  return /** @type{?proto.hedgehog.protocol.proto.AnalogUpdate} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_io_pb.AnalogUpdate, 4));
};


/** @param {?proto.hedgehog.protocol.proto.AnalogUpdate|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setAnalogUpdate = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearAnalogUpdate = function() {
  this.setAnalogUpdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasAnalogUpdate = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional DigitalRequest digital_request = 5;
 * @return {?proto.hedgehog.protocol.proto.DigitalRequest}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getDigitalRequest = function() {
  return /** @type{?proto.hedgehog.protocol.proto.DigitalRequest} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_io_pb.DigitalRequest, 5));
};


/** @param {?proto.hedgehog.protocol.proto.DigitalRequest|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setDigitalRequest = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearDigitalRequest = function() {
  this.setDigitalRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasDigitalRequest = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional DigitalUpdate digital_update = 6;
 * @return {?proto.hedgehog.protocol.proto.DigitalUpdate}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getDigitalUpdate = function() {
  return /** @type{?proto.hedgehog.protocol.proto.DigitalUpdate} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_io_pb.DigitalUpdate, 6));
};


/** @param {?proto.hedgehog.protocol.proto.DigitalUpdate|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setDigitalUpdate = function(value) {
  jspb.Message.setOneofWrapperField(this, 6, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearDigitalUpdate = function() {
  this.setDigitalUpdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasDigitalUpdate = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional MotorAction motor_action = 7;
 * @return {?proto.hedgehog.protocol.proto.MotorAction}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getMotorAction = function() {
  return /** @type{?proto.hedgehog.protocol.proto.MotorAction} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_motor_pb.MotorAction, 7));
};


/** @param {?proto.hedgehog.protocol.proto.MotorAction|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setMotorAction = function(value) {
  jspb.Message.setOneofWrapperField(this, 7, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearMotorAction = function() {
  this.setMotorAction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasMotorAction = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional MotorRequest motor_request = 8;
 * @return {?proto.hedgehog.protocol.proto.MotorRequest}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getMotorRequest = function() {
  return /** @type{?proto.hedgehog.protocol.proto.MotorRequest} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_motor_pb.MotorRequest, 8));
};


/** @param {?proto.hedgehog.protocol.proto.MotorRequest|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setMotorRequest = function(value) {
  jspb.Message.setOneofWrapperField(this, 8, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearMotorRequest = function() {
  this.setMotorRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasMotorRequest = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional MotorUpdate motor_update = 9;
 * @return {?proto.hedgehog.protocol.proto.MotorUpdate}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getMotorUpdate = function() {
  return /** @type{?proto.hedgehog.protocol.proto.MotorUpdate} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_motor_pb.MotorUpdate, 9));
};


/** @param {?proto.hedgehog.protocol.proto.MotorUpdate|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setMotorUpdate = function(value) {
  jspb.Message.setOneofWrapperField(this, 9, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearMotorUpdate = function() {
  this.setMotorUpdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasMotorUpdate = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional MotorStateUpdate motor_state_update = 10;
 * @return {?proto.hedgehog.protocol.proto.MotorStateUpdate}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getMotorStateUpdate = function() {
  return /** @type{?proto.hedgehog.protocol.proto.MotorStateUpdate} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_motor_pb.MotorStateUpdate, 10));
};


/** @param {?proto.hedgehog.protocol.proto.MotorStateUpdate|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setMotorStateUpdate = function(value) {
  jspb.Message.setOneofWrapperField(this, 10, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearMotorStateUpdate = function() {
  this.setMotorStateUpdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasMotorStateUpdate = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional MotorSetPositionAction motor_set_position_action = 11;
 * @return {?proto.hedgehog.protocol.proto.MotorSetPositionAction}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getMotorSetPositionAction = function() {
  return /** @type{?proto.hedgehog.protocol.proto.MotorSetPositionAction} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_motor_pb.MotorSetPositionAction, 11));
};


/** @param {?proto.hedgehog.protocol.proto.MotorSetPositionAction|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setMotorSetPositionAction = function(value) {
  jspb.Message.setOneofWrapperField(this, 11, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearMotorSetPositionAction = function() {
  this.setMotorSetPositionAction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasMotorSetPositionAction = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional ServoAction servo_action = 12;
 * @return {?proto.hedgehog.protocol.proto.ServoAction}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getServoAction = function() {
  return /** @type{?proto.hedgehog.protocol.proto.ServoAction} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_servo_pb.ServoAction, 12));
};


/** @param {?proto.hedgehog.protocol.proto.ServoAction|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setServoAction = function(value) {
  jspb.Message.setOneofWrapperField(this, 12, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearServoAction = function() {
  this.setServoAction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasServoAction = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional ProcessExecuteRequest process_execute_request = 13;
 * @return {?proto.hedgehog.protocol.proto.ProcessExecuteRequest}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getProcessExecuteRequest = function() {
  return /** @type{?proto.hedgehog.protocol.proto.ProcessExecuteRequest} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_process_pb.ProcessExecuteRequest, 13));
};


/** @param {?proto.hedgehog.protocol.proto.ProcessExecuteRequest|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setProcessExecuteRequest = function(value) {
  jspb.Message.setOneofWrapperField(this, 13, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearProcessExecuteRequest = function() {
  this.setProcessExecuteRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasProcessExecuteRequest = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional ProcessExecuteReply process_execute_reply = 14;
 * @return {?proto.hedgehog.protocol.proto.ProcessExecuteReply}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getProcessExecuteReply = function() {
  return /** @type{?proto.hedgehog.protocol.proto.ProcessExecuteReply} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_process_pb.ProcessExecuteReply, 14));
};


/** @param {?proto.hedgehog.protocol.proto.ProcessExecuteReply|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setProcessExecuteReply = function(value) {
  jspb.Message.setOneofWrapperField(this, 14, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearProcessExecuteReply = function() {
  this.setProcessExecuteReply(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasProcessExecuteReply = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional ProcessStreamAction process_stream_action = 15;
 * @return {?proto.hedgehog.protocol.proto.ProcessStreamAction}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getProcessStreamAction = function() {
  return /** @type{?proto.hedgehog.protocol.proto.ProcessStreamAction} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_process_pb.ProcessStreamAction, 15));
};


/** @param {?proto.hedgehog.protocol.proto.ProcessStreamAction|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setProcessStreamAction = function(value) {
  jspb.Message.setOneofWrapperField(this, 15, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearProcessStreamAction = function() {
  this.setProcessStreamAction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasProcessStreamAction = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional ProcessStreamUpdate process_stream_update = 16;
 * @return {?proto.hedgehog.protocol.proto.ProcessStreamUpdate}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getProcessStreamUpdate = function() {
  return /** @type{?proto.hedgehog.protocol.proto.ProcessStreamUpdate} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_process_pb.ProcessStreamUpdate, 16));
};


/** @param {?proto.hedgehog.protocol.proto.ProcessStreamUpdate|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setProcessStreamUpdate = function(value) {
  jspb.Message.setOneofWrapperField(this, 16, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearProcessStreamUpdate = function() {
  this.setProcessStreamUpdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasProcessStreamUpdate = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional ProcessExitUpdate process_exit_update = 17;
 * @return {?proto.hedgehog.protocol.proto.ProcessExitUpdate}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.getProcessExitUpdate = function() {
  return /** @type{?proto.hedgehog.protocol.proto.ProcessExitUpdate} */ (
    jspb.Message.getWrapperField(this, hedgehog_protocol_proto_process_pb.ProcessExitUpdate, 17));
};


/** @param {?proto.hedgehog.protocol.proto.ProcessExitUpdate|undefined} value */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.setProcessExitUpdate = function(value) {
  jspb.Message.setOneofWrapperField(this, 17, proto.hedgehog.protocol.proto.HedgehogMessage.oneofGroups_[0], value);
};


proto.hedgehog.protocol.proto.HedgehogMessage.prototype.clearProcessExitUpdate = function() {
  this.setProcessExitUpdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.hedgehog.protocol.proto.HedgehogMessage.prototype.hasProcessExitUpdate = function() {
  return jspb.Message.getField(this, 17) != null;
};


goog.object.extend(exports, proto.hedgehog.protocol.proto);
