/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.hedgehog.protocol.proto.ServoAction', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hedgehog.protocol.proto.ServoAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hedgehog.protocol.proto.ServoAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.hedgehog.protocol.proto.ServoAction.displayName = 'proto.hedgehog.protocol.proto.ServoAction';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hedgehog.protocol.proto.ServoAction.prototype.toObject = function(opt_includeInstance) {
  return proto.hedgehog.protocol.proto.ServoAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hedgehog.protocol.proto.ServoAction} msg The msg instance to transform.
 * @return {!Object}
 */
proto.hedgehog.protocol.proto.ServoAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    port: jspb.Message.getFieldWithDefault(msg, 1, 0),
    active: jspb.Message.getFieldWithDefault(msg, 2, false),
    position: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hedgehog.protocol.proto.ServoAction}
 */
proto.hedgehog.protocol.proto.ServoAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hedgehog.protocol.proto.ServoAction;
  return proto.hedgehog.protocol.proto.ServoAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hedgehog.protocol.proto.ServoAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hedgehog.protocol.proto.ServoAction}
 */
proto.hedgehog.protocol.proto.ServoAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPort(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setActive(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPosition(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.hedgehog.protocol.proto.ServoAction} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.hedgehog.protocol.proto.ServoAction.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hedgehog.protocol.proto.ServoAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.hedgehog.protocol.proto.ServoAction.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getPort();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = this.getActive();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = this.getPosition();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
};


/**
 * optional uint32 port = 1;
 * @return {number}
 */
proto.hedgehog.protocol.proto.ServoAction.prototype.getPort = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.hedgehog.protocol.proto.ServoAction.prototype.setPort = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional bool active = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.hedgehog.protocol.proto.ServoAction.prototype.getActive = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.hedgehog.protocol.proto.ServoAction.prototype.setActive = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional uint32 position = 3;
 * @return {number}
 */
proto.hedgehog.protocol.proto.ServoAction.prototype.getPosition = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.hedgehog.protocol.proto.ServoAction.prototype.setPosition = function(value) {
  jspb.Message.setField(this, 3, value);
};


goog.object.extend(exports, proto.hedgehog.protocol.proto);
