language: node_js
sudo: false

node_js:
  - 11
  - 10
  - 9
  - 8
  - 7
  - 6

install:
  - wget https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
  - unzip protoc-3.6.1-linux-x86_64.zip
  - PATH=./bin:$PATH
  - npm install
  - grunt protoc

# command to run tests
script:
  - grunt tslint
  - grunt build
  - npm test
  - npm run coveralls
