language: node_js

node_js:
  - 8
  - 7
  - 6
  - 4
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libzmq3
      - libzmq3-dev

install:
  - wget https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
  - unzip protoc-3.6.1-linux-x86_64.zip
  - PATH=./bin:$PATH
  - npm install
  - grunt protoc

# command to run tests
script:
  - grunt tslint
  - grunt build
  - npm test
  - npm run coveralls

notifications:
  slack:
    rooms:
      secure: nEnh7ifKc34lZkpvon7e6xyLUlvQN3XaOQoRRTB8H9fXeA1+qVT5UD9770calMQ2TJZ1D6oyjuqIdpmHsrSfS6la/cGDkU6ql4kwRCw/y/k9OQM3RaAj0z3pVRDdwc/8zQ0F9q4S1wdVjtHE/u6Z1W5MYjafzhvpVu6QlEJU13PZs/Jpp7lAdzZVr6aCNo/nAJQrSmHbal4VqGQL/H9w0N+UqMPazgYpy94wpDQlWUmciT7tmZaWYA1W6/pIcQWkJLET5Zs8YL6wEuDraeoJe9WKM05C2e6N1lfqgoAi60bxnJl0r544Z0GVoPxTn3DUUN/pU7ipazhPNMuNOfrZPOCBpbMwylCrZzdysgxHXFNTj9sOZhZ1hJ2gaDEjrnMiz4p5QP6k3D/2Hgn1uweTARXM9idFCL8UDB8izyfdCblQxydhmFKDguxlWXI2appQYU3YcGmOgCKGXgr9pCrLVAoidZcyRusUh+cLNWq32suDd3n23cbN2HEPJxmQrBrhkap8ZS3BHqCqneOe/UtelmInQMVNZfgaDYMIEw07Tg9YzAyAMT1NflWctGWAAu90x5pLUGgpIHZI6EmNXOwanfl1Tgo+BQqsZnyqPAB8KSRaMWkUdp7ZzHJGGDAgIGm7Gftu8pVqjGVV0AODxi/A5hnW5EVpLuB2YYeb//hT6N8=
    on_success: change
    on_failure: always
